// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSKq8EE9I1YoPx7d6Bn05R5FTGDJxhAYU',
    appId: '1:460874215224:android:2e95cd95b29aba2ee69bcd',
    messagingSenderId: '460874215224',
    projectId: 'epcc-38d4a',
    databaseURL: 'https://epcc-38d4a-default-rtdb.firebaseio.com',
    storageBucket: 'epcc-38d4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-zhtkpIzII8UOsIjc1GEHbv-u1wraPh8',
    appId: '1:460874215224:ios:110ebcb953ee3836e69bcd',
    messagingSenderId: '460874215224',
    projectId: 'epcc-38d4a',
    databaseURL: 'https://epcc-38d4a-default-rtdb.firebaseio.com',
    storageBucket: 'epcc-38d4a.appspot.com',
    iosClientId: '460874215224-edhln8j15hobgvv6onrkolo8i99p7hok.apps.googleusercontent.com',
    iosBundleId: 'com.virtuenetz.epcc',
  );
}
